name: Build and Deploy Quarto Website

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'

    - name: Install Quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.551/quarto-1.4.551-linux-amd64.tar.gz
        mkdir ~/opt
        tar -C ~/opt -xvzf quarto-1.4.551-linux-amd64.tar.gz
        mkdir ~/bin
        ln -s ~/opt/quarto-1.4.551/bin/quarto ~/bin/quarto
        ( echo ""; echo 'export PATH=$PATH:~/bin\n' ; echo "" ) >> ~/.profile
        source ~/.profile
        quarto check

    - name: Build Quarto Website
      run: quarto render

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # default build directory for Quarto
