name: Build and Deploy Quarto Website on Windows

on:
  push:
    branches:
      - main  # Adjust this to your repository's default branch if different

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Install Quarto
      run: |
        Invoke-WebRequest -Uri "https://quarto.org/download/latest/windows" -OutFile "quarto-installer.exe"
        Start-Process -FilePath "quarto-installer.exe" -ArgumentList '/S' -Wait

    - name: Build Quarto Website
      run: quarto render

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # The default output directory for Quarto projects
